# Generated by Django 5.2 on 2026-04-16 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_count', models.PositiveIntegerField(default=0)),
                ('signal_count', models.PositiveIntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('signal_type', models.CharField(choices=[('mass_hiring', 'Mass hiring'), ('hiring_activity', 'Hiring activity'), ('recruiting_signal', 'Recruiting signal')], max_length=50)),
                ('source_url', models.URLField(max_length=500)),
                ('matched_keywords', models.JSONField(default=list)),
                ('signal_score', models.PositiveIntegerField()),
                ('detected_at', models.DateTimeField()),
                ('reason', models.TextField()),
                ('title', models.CharField(max_length=500)),
                ('published_at', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='detector.detectionrun')),
            ],
            options={
                'ordering': ['-signal_score', '-detected_at'],
            },
        ),
    ]
